apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-tools-app
  namespace: saas-tools
  labels:
    app: saas-tools
spec:
  replicas: 3
  selector:
    matchLabels:
      app: saas-tools
  template:
    metadata:
      labels:
        app: saas-tools
    spec:
      containers:
      - name: app
        image: saas-tools:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: saas-tools-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: saas-tools-secrets
              key: jwt-secret
        - name: RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              name: saas-tools-secrets
              key: razorpay-key-id
        - name: RAZORPAY_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: saas-tools-secrets
              key: razorpay-key-secret
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"